/*Elabora una lista de contactos
Inicialmente tendrá los valores de la tabla adjunta:
Declara e inicializa las variables donde se almacenará toda la información (nueve variables en total).
 Muestra en la consola información sobre el primer y último contacto en el formulario: nombre/teléfono/correo.*/


let nombre1 = "Maxwell Wright";
let nombre2 = "Raja Villarreal";
let nombre3 = "Helen Richards";

let telefono1 = "(0191) 719 6495";
let telefono2 = "0866 398 2895";
let telefono3 = "0800 1111";

let email1 = "Curabitur.egestas.nunc@nonummyac.co.uk";
let email2 = "posuere.vulputate@sed.com";
let email3 = "libero@convallis.edu";

console.log(nombre1 + "/" +  telefono1 + "/" + email1);
console.log(nombre3 + "/" +  telefono3 + "/" + email3);